name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release distributables for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.13.0
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Bootstrap the plugins
        run: yarn bootstrap:plugins:all
      - name: Build plugins
        run: yarn build:plugins:all
      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.0.0
        with:
          release: true
          github_token: ${{ secrets.GH_TOKEN }}
          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          # windows code signing certificate
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
